# DISCLAIMER
# Changing any of the lists, dictionaries etc. of this file, the sequence of values or any other modifications,
# might affect values in other files. Please check where a variable is used before modifying it.

from ..const.build.appendiks_overblik_opbyg import (
    STRUCTURE_OVERVIEW,
    GWP_A1_A3,
    GWP_A4,
    GWP_A5,
    GWP_B4,
    GWP_C3,
    GWP_C4,
    GWP_D,
)
from ..const.settings import (
    STUDY_PERIOD,
    EMISSION_FACTOR,
    LIFE_CYCLE_PHASES,
    INCLUDE_DEMOLITION,
    SEQUESTRATION_INCLUDE,
    CALCULATE_PEOPLE,
    ELECTRICITY_USE,
    EMISSION_FACTOR_DIESEL,
    DIESEL_USE,
)

from ..const.typology_values import (
    WWR_DICT,
    LIVE_LOAD_DICT,
    SPAN_DICT,
    OCCUPANCY_DICT,
    LENGTH_CORE_DICT,
    ROOF_ANGLE,
    INTERNAL_WALLS_LENGTH_DICT_M,
    INTERNAL_WALLS_LENGTH_DICT,
    MIN_FTC,
    MIN_FTC_BASEMENT,
    MIN_FLOORS_STAIRS_DICT,
    MIN_FLOORS_CORE_DICT,
    MAX_AREA_CORE_DICT,
    FLOOR_FINISH_DICT,
    CEILING_FINISH_DICT,
    TECHNICAL_SYSTEMS_DICT,
    ENERGY_USE_DICT,
    HEATING_DICT,
    STRUCTURE_DICT,
)
from ..const.build.categorical import (
    PARKING_BASEMENT,
    CONDITION_LIST,
    TYPOLOGY,
    NO_BASEMENT_TYPOLOGY,
    STRUCTURE_LIST,
    FACADE,
    ROOF_TYPE,
    ROOF_MATERIAL,
    HEATING_SOURCE,
    HEATING_DEFAULT,
)

from ..const.build.numbers import (
    AREA_MIN,
    DEPTH_RANGE,
    CIRCUMFERENCE_MIN,
    HEIGHT_RANGE,
    NUM_FLOORS_RANGE,
    FTF_RANGE,
    NUM_BASEMENT_FLOORS_RANGE,
    WWR_RANGE,
    CORE_LENGTH,
)


from ..const.build.structure import (
    VERTICAL_STRUCTURE,
    BEAM_STRUCTURE,
    SLAB_STRUCTURE,
    SLAB_THICKNESS,
    PAD_FOUNDATION,
    LINE_FOUNDATION,
    CORE_WALL,
    INTERNAL_WALLS,
    DEMOLITION_DICT,
)

from ..const.build.material_used import BUILDING_CONDITION
from ..const.ml_region import MODEL_TYPOS

from ..const.build.emissionsfaktor import emission_factor_lookup_table

from ..const.land.numbers import (
    AREA_MIN_LANDSCAPE,
    LENGTH_MIN_LANDSCAPE,
    WIDTH_MIN_LANDSCAPE,
    NUM_TREES_MIN,
    NUM_SHRUBS_MIN,
)
from ..const.land.categorical import (
    CATEGORY_LANDSCAPE,
    TYPE_LANDSCAPE,
    TYPE_TREES,
    SIZE_TREES,
    TYPE_SHRUBS,
    SIZE_SHRUBS,
    CONDITION_LANSCAPE,
)

from ..const.land.road import ROAD_WIDTH_DICT
from ..const.land.selection import (
    ASSEMBLY_SELECTION_LANDSCAPE,
    ASSEMBLY_SELECTION_TREES,
    ASSEMBLY_SELECTION_SHRUBS,
)

from ..const.land.overblik_opbyg import (
    GWP_A1_A3_LANDSCAPE,
    GWP_A4_LANDSCAPE,
    GWP_A5_LANDSCAPE,
    GWP_B4_LANDSCAPE,
    GWP_B6_LANDSCAPE,
    GWP_C3_LANDSCAPE,
    GWP_C4_LANDSCAPE,
    GWP_D_LANDSCAPE,
)

constants = {
    # SETTINGS
    "STUDY_PERIOD": STUDY_PERIOD,
    "EMISSION_FACTOR": EMISSION_FACTOR,
    "LIFE_CYCLE_PHASES": LIFE_CYCLE_PHASES,
    "INCLUDE_DEMOLITION": INCLUDE_DEMOLITION,
    "SEQUESTRATION_INCLUDE": SEQUESTRATION_INCLUDE,
    "CALCULATE_PEOPLE": CALCULATE_PEOPLE,
    "ELECTRICITY_USE": ELECTRICITY_USE,
    "EMISSION_FACTOR_DIESEL": EMISSION_FACTOR_DIESEL,
    "DIESEL_USE": DIESEL_USE,
    # MODEL_TYPOS
    "MODEL_TYPOS": MODEL_TYPOS,
    # TYPOLOGY_VALUES
    "WWR_DICT": WWR_DICT,
    "LIVE_LOAD_DICT": LIVE_LOAD_DICT,
    "SPAN_DICT": SPAN_DICT,
    "OCCUPANCY_DICT": OCCUPANCY_DICT,
    "LENGTH_CORE_DICT": LENGTH_CORE_DICT,
    "ROOF_ANGLE": ROOF_ANGLE,
    "INTERNAL_WALLS_LENGTH_DICT_M": INTERNAL_WALLS_LENGTH_DICT_M,
    "INTERNAL_WALLS_LENGTH_DICT": INTERNAL_WALLS_LENGTH_DICT,
    "MIN_FTC": MIN_FTC,
    "MIN_FTC_BASEMENT": MIN_FTC_BASEMENT,
    "MIN_FLOORS_STAIRS_DICT": MIN_FLOORS_STAIRS_DICT,
    "MIN_FLOORS_CORE_DICT": MIN_FLOORS_CORE_DICT,
    "MAX_AREA_CORE_DICT": MAX_AREA_CORE_DICT,
    "FLOOR_FINISH_DICT": FLOOR_FINISH_DICT,
    "CEILING_FINISH_DICT": CEILING_FINISH_DICT,
    "TECHNICAL_SYSTEMS_DICT": TECHNICAL_SYSTEMS_DICT,
    "ENERGY_USE_DICT": ENERGY_USE_DICT,
    "HEATING_DICT": HEATING_DICT,
    "STRUCTURE_DICT": STRUCTURE_DICT,
    # CATEGORICAL
    "PARKING_BASEMENT": PARKING_BASEMENT,
    "CONDITION_LIST": CONDITION_LIST,
    "TYPOLOGY": TYPOLOGY,
    "NO_BASEMENT_TYPOLOGY": NO_BASEMENT_TYPOLOGY,
    "STRUCTURE_LIST": STRUCTURE_LIST,
    "FACADE": FACADE,
    "ROOF_TYPE": ROOF_TYPE,
    "ROOF_MATERIAL": ROOF_MATERIAL,
    "HEATING_SOURCE": HEATING_SOURCE,
    "HEATING_DEFAULT": HEATING_DEFAULT,
    # BUILDING ---------------------------------------------------------
    # NUMBERS ----------------------------
    "AREA_MIN": AREA_MIN,
    "DEPTH_RANGE": DEPTH_RANGE,
    "CIRCUMFERENCE_MIN": CIRCUMFERENCE_MIN,
    "HEIGHT_RANGE": HEIGHT_RANGE,
    "NUM_FLOORS_RANGE": NUM_FLOORS_RANGE,
    "FTF_RANGE": FTF_RANGE,
    "NUM_BASEMENT_FLOORS_RANGE": NUM_BASEMENT_FLOORS_RANGE,
    "WWR_RANGE": WWR_RANGE,
    "CORE_LENGTH": CORE_LENGTH,
    # STRUCTURE --------------------------
    "VERTICAL_STRUCTURE": VERTICAL_STRUCTURE,
    "BEAM_STRUCTURE": BEAM_STRUCTURE,
    "SLAB_STRUCTURE": SLAB_STRUCTURE,
    "SLAB_THICKNESS": SLAB_THICKNESS,
    "PAD_FOUNDATION": PAD_FOUNDATION,
    "LINE_FOUNDATION": LINE_FOUNDATION,
    "CORE_WALL": CORE_WALL,
    "INTERNAL_WALLS": INTERNAL_WALLS,
    "DEMOLITION_DICT": DEMOLITION_DICT,
    # MATERIAL_USED --------------------------
    "BUILDING_CONDITION": BUILDING_CONDITION,
    # EMISSIONSFAKTOR --------------------------
    "emission_factor_lookup_table": emission_factor_lookup_table,
    # STRUCTURE_OVERVIEW --------------------------
    "STRUCTURE_OVERVIEW": STRUCTURE_OVERVIEW,
    "GWP_A1_A3": GWP_A1_A3,
    "GWP_A4": GWP_A4,
    "GWP_A5": GWP_A5,
    "GWP_B4": GWP_B4,
    "GWP_C3": GWP_C3,
    "GWP_C4": GWP_C4,
    "GWP_D": GWP_D,
    # BUILDING ---------------------------------------------------------
    # NUMBERS ----------------------------
    "AREA_MIN_LANDSCAPE": AREA_MIN_LANDSCAPE,
    "LENGTH_MIN_LANDSCAPE": LENGTH_MIN_LANDSCAPE,
    "WIDTH_MIN_LANDSCAPE": WIDTH_MIN_LANDSCAPE,
    "NUM_TREES_MIN": NUM_TREES_MIN,
    "NUM_SHRUBS_MIN": NUM_SHRUBS_MIN,
    # CATEGORICAL --------------------------
    "CATEGORY_LANDSCAPE": CATEGORY_LANDSCAPE,
    "TYPE_LANDSCAPE": TYPE_LANDSCAPE,
    "TYPE_TREES": TYPE_TREES,
    "SIZE_TREES": SIZE_TREES,
    "TYPE_SHRUBS": TYPE_SHRUBS,
    "SIZE_SHRUBS": SIZE_SHRUBS,
    "CONDITION_LANSCAPE": CONDITION_LANSCAPE,
    # ROAD --------------------------
    "ROAD_WIDTH_DICT": ROAD_WIDTH_DICT,
    # ASSEMBLY_SELECTION --------------------------
    "ASSEMBLY_SELECTION_LANDSCAPE": ASSEMBLY_SELECTION_LANDSCAPE,
    "ASSEMBLY_SELECTION_TREES": ASSEMBLY_SELECTION_TREES,
    "ASSEMBLY_SELECTION_SHRUBS": ASSEMBLY_SELECTION_SHRUBS,
    # GWP --------------------------
    "GWP_A1_A3_LANDSCAPE": GWP_A1_A3_LANDSCAPE,
    "GWP_A4_LANDSCAPE": GWP_A4_LANDSCAPE,
    "GWP_A5_LANDSCAPE": GWP_A5_LANDSCAPE,
    "GWP_B4_LANDSCAPE": GWP_B4_LANDSCAPE,
    "GWP_B6_LANDSCAPE": GWP_B6_LANDSCAPE,
    "GWP_C3_LANDSCAPE": GWP_C3_LANDSCAPE,
    "GWP_C4_LANDSCAPE": GWP_C4_LANDSCAPE,
    "GWP_D_LANDSCAPE": GWP_D_LANDSCAPE,
}
