# region Dictionaries to assign default values based on typology
WWR_DICT = {
    "detached house": 0.22,
    "terraced house": 0.25,
    "apartment building": 0.30,
    "office": 0.40,
    "school": 0.25,
    "institution": 0.25,
    "retail": 0.60,
    "parking": 0.00,
    "industry": 0.20,
    "transport": 0.20,
    "hotel": 0.30,
    "hospital": 0.30,
}

LIVE_LOAD_DICT = {
    "detached house": 1.5,
    "terraced house": 1.5,
    "apartment building": 1.5,
    "office": 2.5,
    "school": 2.5,
    "institution": 2.5,
    "retail": 4.0,
    "parking": 2.5,
    "industry": 7.5,
    "transport": 5.0,
    "hotel": 1.5,
    "hospital": 2.5,
}

SPAN_DICT = {
    "detached house": 6,
    "terraced house": 6,
    "apartment building": 6,
    "office": 8,
    "school": 8,
    "institution": 8,
    "retail": 8,
    "parking": 8,
    "industry": 8,
    "transport": 8,
    "hotel": 6,
    "hospital": 8,
}

OCCUPANCY_DICT = {
    "detached house": 59,
    "terraced house": 50,
    "apartment building": 44,
    "office": 12,
    "school": 0,
    "institution": 0,
    "retail": 0,
    "parking": 0,
    "industry": 0,
    "transport": 0,
    "hotel": 0,
    "hospital": 0,
}

LENGTH_CORE_DICT = {
    "detached house": 0.0,
    "terraced house": 0.0,
    "apartment building": 5.0,
    "office": 5.0,
    "school": 5.0,
    "institution": 5.0,
    "retail": 5.0,
    "parking": 5.0,
    "industry": 5.0,
    "transport": 5.0,
    "hotel": 5.0,
    "hospital": 5.0,
}

ROOF_ANGLE = {
    "detached house": 30,
    "terraced house": 30,
    "apartment building": 30,
    "office": 30,
    "school": 30,
    "institution": 30,
    "retail": 30,
    "parking": 30,
    "industry": 30,
    "transport": 30,
    "hotel": 30,
    "hospital": 30,
}

INTERNAL_WALLS_LENGTH_DICT_M = {
    "detached house": 0.0000,
    "terraced house": 0.0000,
    "apartment building": 0.0000,
    "office": 0.0000,
    "school": 0.0000,
    "institution": 0.0000,
    "retail": 0.0000,
    "parking": 0.0000,
    "industry": 0.0000,
    "transport": 0.0000,
    "hotel": 0.0000,
    "hospital": 0.0000,
}

INTERNAL_WALLS_LENGTH_DICT = {
    "detached house": 0.2,
    "terraced house": 0.25,
    "apartment building": 0.15,
    "office": 0.25,
    "school": 0.25,
    "institution": 0.25,
    "retail": 0.1,
    "parking": 0.01,
    "industry": 0.01,
    "transport": 0.01,
    "hotel": 0.25,
    "hospital": 0.25,
}

MIN_FTC = {
    "detached house": 2.3,
    "terraced house": 2.3,
    "apartment building": 2.5,
    "office": 2.5,
    "school": 2.3,
    "institution": 2.3,
    "retail": 2.5,
    "parking": 2.1,
    "industry": 2.5,
    "transport": 2.5,
    "hotel": 2.3,
    "hospital": 2.5,
}

MIN_FTC_BASEMENT = {
    "detached house": 2.3,
    "terraced house": 2.3,
    "apartment building": 2.3,
    "office": 2.3,
    "school": 2.3,
    "institution": 2.3,
    "retail": 2.3,
    "parking": 2.1,
    "industry": 2.3,
    "transport": 2.3,
    "hotel": 2.3,
    "hospital": 2.3,
}

MIN_FLOORS_STAIRS_DICT = {
    "detached house": 2,
    "terraced house": 2,
    "apartment building": 2,
    "office": 2,
    "school": 2,
    "institution": 2,
    "retail": 2,
    "parking": 2,
    "industry": 2,
    "transport": 2,
    "hotel": 2,
    "hospital": 2,
}

MIN_FLOORS_CORE_DICT = {
    "detached house": 4,
    "terraced house": 4,
    "apartment building": 4,
    "office": 4,
    "school": 4,
    "institution": 4,
    "retail": 4,
    "parking": 4,
    "industry": 4,
    "transport": 4,
    "hotel": 4,
    "hospital": 4,
}

MAX_AREA_CORE_DICT = {
    "detached house": 400,
    "terraced house": 400,
    "apartment building": 400,
    "office": 800,
    "school": 800,
    "institution": 800,
    "retail": 800,
    "parking": 1200,
    "industry": 1200,
    "transport": 1200,
    "hotel": 800,
    "hospital": 1200,
}

FLOOR_FINISH_DICT = {
    "detached house": "timber finish",
    "terraced house": "timber finish",
    "apartment building": "timber finish",
    "office": "linoleum finish",
    "school": "linoleum finish",
    "institution": "linoleum finish",
    "retail": "concrete finish",
    "parking": "concrete finish",
    "industry": "concrete finish",
    "transport": "concrete finish",
    "hotel": "linoleum finish",
    "hospital": "linoleum finish",
}

CEILING_FINISH_DICT = {
    "detached house": "gypsum ceiling",
    "terraced house": "gypsum ceiling",
    "apartment building": "gypsum ceiling",
    "office": "suspended ceiling",
    "school": "suspended ceiling",
    "institution": "suspended ceiling",
    "retail": "suspended ceiling",
    "parking": "suspended ceiling",
    "industry": "suspended ceiling",
    "transport": "suspended ceiling",
    "hotel": "suspended ceiling",
    "hospital": "suspended ceiling",
}

TECHNICAL_SYSTEMS_DICT = {
    "detached house": "detached house",
    "terraced house": "terraced house",
    "apartment building": "apartment building",
    "office": "office",
    "school": "others",
    "institution": "others",
    "retail": "others",
    "parking": "others",
    "industry": "others",
    "transport": "others",
    "hotel": "others",
    "hospital": "others",
}

ENERGY_USE_DICT = {
    "detached house": {
        "new": 3.0,
        "transformation": 3.0,
        "renovation": 3.0,
        "refurbishment": 3.0,
        "keep": 3.0,
        "demolition": 0.0,
    },
    "terraced house": {
        "new": 3.0,
        "transformation": 3.0,
        "renovation": 3.0,
        "refurbishment": 3.0,
        "keep": 3.0,
        "demolition": 0.0,
    },
    "apartment building": {
        "new": 3.0,
        "transformation": 3.0,
        "renovation": 3.0,
        "refurbishment": 3.0,
        "keep": 3.0,
        "demolition": 0.0,
    },
    "office": {
        "new": 7.0,
        "transformation": 7.0,
        "renovation": 7.0,
        "refurbishment": 7.0,
        "keep": 7.0,
        "demolition": 0.0,
    },
    "school": {
        "new": 7.0,
        "transformation": 7.0,
        "renovation": 7.0,
        "refurbishment": 7.0,
        "keep": 7.0,
        "demolition": 0.0,
    },
    "institution": {
        "new": 7.0,
        "transformation": 7.0,
        "renovation": 7.0,
        "refurbishment": 7.0,
        "keep": 7.0,
        "demolition": 0.0,
    },
    "retail": {
        "new": 7.0,
        "transformation": 7.0,
        "renovation": 7.0,
        "refurbishment": 7.0,
        "keep": 7.0,
        "demolition": 0.0,
    },
    "parking": {
        "new": 7.0,
        "transformation": 7.0,
        "renovation": 7.0,
        "refurbishment": 7.0,
        "keep": 7.0,
        "demolition": 0.0,
    },
    "industry": {
        "new": 7.0,
        "transformation": 7.0,
        "renovation": 7.0,
        "refurbishment": 7.0,
        "keep": 7.0,
        "demolition": 0.0,
    },
    "transport": {
        "new": 7.0,
        "transformation": 7.0,
        "renovation": 7.0,
        "refurbishment": 7.0,
        "keep": 7.0,
        "demolition": 0.0,
    },
    "hotel": {
        "new": 7.0,
        "transformation": 7.0,
        "renovation": 7.0,
        "refurbishment": 7.0,
        "keep": 7.0,
        "demolition": 0.0,
    },
    "hospital": {
        "new": 7.0,
        "transformation": 7.0,
        "renovation": 7.0,
        "refurbishment": 7.0,
        "keep": 7.0,
        "demolition": 0.0,
    },
}
HEATING_DICT = {
    "detached house": {
        "new": 45.651612,
        "transformation": 45.651612,
        "renovation": 45.651612,
        "refurbishment": 112.833521,
        "keep": 112.833521,
        "demolition": 0.0,
    },
    "terraced house": {
        "new": 46.720917,
        "transformation": 46.720917,
        "renovation": 46.720917,
        "refurbishment": 108.273991,
        "keep": 108.273991,
        "demolition": 0.0,
    },
    "apartment building": {
        "new": 65.718513,
        "transformation": 65.718513,
        "renovation": 65.718513,
        "refurbishment": 118.555336,
        "keep": 118.555336,
        "demolition": 0.0,
    },
    "office": {
        "new": 48.734643,
        "transformation": 48.734643,
        "renovation": 48.734643,
        "refurbishment": 99.664250,
        "keep": 99.664250,
        "demolition": 0.0,
    },
    "school": {
        "new": 55.875899,
        "transformation": 55.875899,
        "renovation": 55.875899,
        "refurbishment": 113.062100,
        "keep": 113.062100,
        "demolition": 0.0,
    },
    "institution": {
        "new": 55.875899,
        "transformation": 55.875899,
        "renovation": 55.875899,
        "refurbishment": 113.062100,
        "keep": 113.062100,
        "demolition": 0.0,
    },
    "retail": {
        "new": 48.734643,
        "transformation": 48.734643,
        "renovation": 48.734643,
        "refurbishment": 99.664250,
        "keep": 99.664250,
        "demolition": 0.0,
    },
    "parking": {
        "new": 0.0,
        "transformation": 0.0,
        "renovation": 0.0,
        "refurbishment": 0.0,
        "keep": 0.0,
        "demolition": 0.0,
    },
    "industry": {
        "new": 48.734643,
        "transformation": 48.734643,
        "renovation": 48.734643,
        "refurbishment": 99.664250,
        "keep": 99.664250,
        "demolition": 0.0,
    },
    "transport": {
        "new": 48.734643,
        "transformation": 48.734643,
        "renovation": 48.734643,
        "refurbishment": 99.664250,
        "keep": 99.664250,
        "demolition": 0.0,
    },
    "hotel": {
        "new": 48.734643,
        "transformation": 48.734643,
        "renovation": 48.734643,
        "refurbishment": 99.664250,
        "keep": 99.664250,
        "demolition": 0.0,
    },
    "hospital": {
        "new": 48.734643,
        "transformation": 48.734643,
        "renovation": 48.734643,
        "refurbishment": 99.664250,
        "keep": 99.664250,
        "demolition": 0.0,
    },
}

STRUCTURE_DICT = {
    "detached house": "concrete (load bearing)",
    "terraced house": "concrete (load bearing)",
    "apartment building": "concrete (load bearing)",
    "office": "concrete (framed)",
    "school": "concrete (framed)",
    "institution": "concrete (framed)",
    "retail": "concrete (framed)",
    "parking": "concrete (framed)",
    "industry": "concrete (framed)",
    "transport": "concrete (framed)",
    "hotel": "concrete (load bearing)",
    "hospital": "concrete (framed)",
}
# endregion
